#===============================================================================
# FreeLing Annotation Presets with named entities
#===============================================================================

languages:
    - cat
    - deu
    - eng
    - spa
    - por


classes:
    sentence: freeling.sentence
    token: freeling.token
    "token:pos": freeling.token:freeling.pos
    "token:baseform": freeling.token:freeling.baseform


presets:
    all:
        - token
        - sentence

    token:
        - freeling.token:freeling.upos
        - freeling.token:freeling.pos
        - freeling.token:freeling.baseform
        - freeling.token:freeling.ne_type

    sentence:
        - <sentence>:misc.id
