#===============================================================================
# Stanford Parser Annotation Presets
#===============================================================================

languages:
    - eng


classes:
    sentence: stanford.sentence
    token: stanford.token
    "token:pos": stanford.token:stanford.pos
    "token:baseform": stanford.token:stanford.baseform
    "token:deprel": <token>:stanford.deprel
    "token:dephead_ref": <token>:stanford.dehead_ref


presets:
    all:
        - token
        - sentence

    token:
        - stanford.token:misc.number_rel_stanford.sentence as ref
        - stanford.token:stanford.pos
        - stanford.token:stanford.upos
        - stanford.token:stanford.baseform
        - stanford.token:stanford.ne_type
        - stanford.token:stanford.dephead_ref
        - stanford.token:stanford.deprel

    sentence:
        - stanford.sentence:misc.id
